# Generated by Django 4.2.28 on 2026-02-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default=1, upload_to='tour_images/'),
            preserve_default=False,
        ),
    ]
