# Generated by Django 4.2.28 on 2026-02-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tour.tourfeature'),
        ),
    ]
