# Generated by Django 4.2.28 on 2026-02-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tourfeature_tour_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
