# Generated by Django 4.2.28 on 2026-02-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='can_swim',
            field=models.BooleanField(default=False, verbose_name='Can swim?'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='medication_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='takes_medication',
            field=models.BooleanField(default=False, verbose_name='Takes medication?'),
        ),
    ]
