# Generated by Django 4.2.28 on 2026-02-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tourbooking_can_swim_tourbooking_medication_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='can_swim',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='medication_details',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='takes_medication',
        ),
    ]
