# Generated by Django 4.2.28 on 2026-02-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_remove_tourbooking_can_swim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان تور'),
        ),
    ]
