# Generated by Django 4.2.28 on 2026-02-17 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0007_alter_tour_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'تور', 'verbose_name_plural': 'تور\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tourbooking',
            options={'verbose_name': 'رزرو تور', 'verbose_name_plural': 'رزروهای تور'},
        ),
        migrations.AlterModelOptions(
            name='tourdate',
            options={'verbose_name': 'تاریخ تور', 'verbose_name_plural': 'تاریخ\u200cهای تور'},
        ),
        migrations.AlterModelOptions(
            name='tourfeature',
            options={'verbose_name': 'ویژگی تور', 'verbose_name_plural': 'ویژگی\u200cهای تور'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'تصویر تور', 'verbose_name_plural': 'تصاویر تور'},
        ),
        migrations.AlterModelOptions(
            name='tourtime',
            options={'verbose_name': 'ساعت تور', 'verbose_name_plural': 'ساعت\u200cهای تور'},
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='can_swim',
            field=models.BooleanField(default=False, verbose_name='می\u200cتواند شنا کند؟'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='medication_details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات دارو'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='takes_medication',
            field=models.BooleanField(default=False, verbose_name='دارو مصرف می\u200cکند؟'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.CharField(max_length=200, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tour.tourfeature', verbose_name='ویژگی\u200cها'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tour_images/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال باشد؟'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ رزرو'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده؟'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد افراد'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='تور'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourdate', verbose_name='تاریخ تور'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourtime', verbose_name='ساعت تور'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tour.tour', verbose_name='تور'),
        ),
        migrations.AlterField(
            model_name='tourfeature',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ویژگی تور'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='tour_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.tour', verbose_name='تور'),
        ),
        migrations.AlterField(
            model_name='tourtime',
            name='time',
            field=models.TimeField(verbose_name='ساعت تور'),
        ),
        migrations.AlterField(
            model_name='tourtime',
            name='tour_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='tour.tourdate', verbose_name='تاریخ تور'),
        ),
    ]
