# Generated by Django 4.2.28 on 2026-02-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_alter_tour_options_alter_tourbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='ظرفیت تور'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.tour'),
        ),
    ]
