# Generated by Django 4.2.28 on 2026-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_tour_capacity_alter_tourbooking_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='agree_to_terms',
            field=models.BooleanField(default=False, verbose_name='قوانین را می\u200cپذیرد؟'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='allergy_details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات حساسیت'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='drinks_alcohol',
            field=models.BooleanField(default=False, verbose_name='مصرف الکل دارد؟'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام تماس اضطراری'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس اضطراری'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='has_allergy',
            field=models.BooleanField(default=False, verbose_name='حساسیت دارد؟'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='has_medical_condition',
            field=models.BooleanField(default=False, verbose_name='بیماری خاص دارد؟'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='language_level',
            field=models.CharField(blank=True, choices=[('none', 'ندارد'), ('basic', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=20, null=True, verbose_name='سطح زبان انگلیسی'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='medical_condition_details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بیماری'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='national_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پاسپورت'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='smokes',
            field=models.BooleanField(default=False, verbose_name='سیگار می\u200cکشد؟'),
        ),
    ]
