# Generated by Django 4.2.28 on 2026-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_tourbooking_agree_to_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='language_level',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True, verbose_name='سطح زبان انگلیسی'),
        ),
    ]
